### ISSUE TITLE
[建議]增加默認轉換方案和繁簡檢測

### ISSUE THREAD

**Issue by AkazaRenn** [fei0316/OpenCC-android-app#1]
因為我一般都是通過長按選擇文字 - Chinese Convert 來轉換的，每次選完還要在一堆菜單裡面選擇有點不方便。不知道能不能支持默認的轉換方案，在菜單中點選之後直接轉換。想要偶爾使用不同的方案時再打開 app 操作。
在這個基礎上再支持繁簡檢測的話，可以同時支持兩套方案，應該就能應對絕大多數用戶的需求了。

**Comment by fei0316** [comment]
感謝你的建議和對本軟件的喜愛。長按轉換的預設轉換方式應該很容易實現，但偵測簡繁自動轉換可能比較複雜，可能需要再研究一下。不知道你有沒有什麼建議？

**Comment by AkazaRenn** [comment]
@fei0316 因爲我沒有做過這方面的工作所以不太能肯定是否可行。我自己的想法是建立一個「繁體字特有漢字表」和一個「簡體字特有漢字表」，從待翻譯的文本中從前往後查找，根據第一個找到的繁體/簡體特有漢字來決定是哪一種，再轉換爲對應語言。只是不知道效率方面是否可以接受。

**Comment by fei0316** [comment]
或者也可以數文字中各有多少個「特有簡體/繁體字」，如果其中一種明顯較多則自動選擇，否則讓用户自行選擇。效率方面估計沒有大問題，畢竟不是用作轉換大量文字（或者設一個限制，只取首數十/數百個字）。
你提議的這兩個功能我也非常感興趣，可惜最近學業繁忙，可能需要過一段時間才能抽空實現。如果您有興趣的話也很歡迎您幫忙加入本功能

**Comment by fei0316** [comment]
最近功課一直都很多，一個不小心就已經過了一個月了，真的十分抱歉。
預設設定功能應該挺簡單的，就在主畫面加個選項就ok了，應該只是幾小時的功夫。
檢測部分剛剛我查了點資料，主要有兩個做法：一是拿一部分（或全部）文字做一次opencc簡繁和繁簡轉換，然後將兩個結果和原文分別比較；二就是像我們説的拿一個特有漢字表，這個方法我找到不少可參考的project，但可惜好像沒有java的: [1](https://github.com/amake/script_detector_2), [2](https://github.com/jpatokal/script_detector), [3](https://github.com/nickdrewe/traditional-or-simplified), [4](https://github.com/tsroten/hanzidentifier)。
如果你有興趣試試做的話，我也可以幫幫忙。

**Comment by AkazaRenn** [comment]
@fei0316 啊真的不好意思，我也是最近工作比較繁忙。聖誕節的時候應該有時間做一下，到時候會在這邊 update 你。真的不好意思

**Comment by AkazaRenn** [comment]
https://gist.github.com/AkazaRenn/533b8064a885ffaa1faaa99f72d4bbc8

這是我做的一個簡單的 string 檢查，因爲實在是不熟悉 Java 的包管理，所以只能把源碼丟上來了。改進方面的話至少`buildMap()`那一塊希望可以儘量少運行，比如只在更新 app 時運行一次。
然後檢查還是選擇了只根據檢查到的第一個“獨有字符”來判斷，因爲如果一個 string 同時存在繁中和簡中的話，本身就不是一個很有意義的對象，結果是哪邊我覺得都可以接受，大不了再轉換一次一定能得到想要的結果。

**Comment by fei0316** [comment]
感謝你的貢獻！終於放假了，這幾天終於有時間處理一下這個project

首先是我看到你用的OpenCC簡繁字表似乎不是獨有字，但看到你有處理簡繁用同一個字的情況？（如「台	臺 檯 颱 台」）
我應該會將自動偵測整合到新的「簡易模式」中，可以直接偵測簡繁並自動轉換，只用OpenCC標準。至於原有能支援各種轉換的進階模式就維持不變，這樣應該ok？另外也可以預設改爲簡易模式。

map的部分我想可以直接在我的電腦產生一次然後存在apk裡就可以了，應該更簡單。

檢查部分你的想法我感覺可以，也可以轉換成功後顯示偵測到是簡或繁並提示如果偵測錯誤可以再轉換一次

另外我的軟件是以GPL3開源，版權部分如果將你的代碼用同樣條款開源並註明貢獻者，可以嗎？另外我在關於頁面的貢獻者部分可以加入你的名字，應該怎樣稱呼你？

再次感謝你的貢獻！我也是第一次收到issue，哈哈

**Comment by AkazaRenn** [comment]
@fei0316 
> 另外我的軟件是以 GPL3 開源，版權部分如果將你的代碼用同樣條款開源並註明貢獻者，可以嗎？另外我在關於頁面的貢獻者部分可以加入你的名字，應該怎樣稱呼你？
沒問題，寫我叫 Renn 就可以了。也謝謝你做的 app！

**Comment by fei0316** [comment]
剛剛已經把功能全部弄好了！如果你有時間的話希望可以幫我測試一下和看看有沒有可以改進的地方。因爲希望再測試下才發佈，我可以直接傳apk給你。如果你能自己compile的話現在repo已經是最新版了

**Comment by AkazaRenn** [comment]
@fei0316 我這邊不太方便 build 的樣子。能不能請你發一個 apk 過來呢？或者可以 release 到 GitHub 打一個 pre-release 的 tag 讓更多人能看到應該也是個好主意。

**Comment by fei0316** [comment]
剛剛已經上傳到Release頁面了！Github的用户不會自動更新，真的發現大問題要修正也不怕影響太多人。如果你有時間的話就幫我測試一下吧！

現在想到兩個問題：一個是有些大家認為是簡體的字其實在繁體也有用（例如广、极），就會導致無法偵測，但如果文字比較長就基本上不會遇到這個問題，二是我現在設定成就算是舊用户更新後也會使用簡易模式，但估計大家對異體字轉換需求不大。我現在是傾向兩個問題都維持現狀。

**Comment by AkazaRenn** [comment]
@fei0316 hl剛剛測試了一下會 crash，包括兩種情況分別是在 app GUI 使用 easy mode 轉換，和開啟自動檢測繁簡後在其他 app 通過 context menu 轉換，都會發生。系統是 Android 11。

**Comment by fei0316** [comment]
處理了！是proguard引致的問題，所以在debug build的時候沒有發生。

**Comment by AkazaRenn** [comment]
@fei0316 感覺很完美！非常感謝！我先把這個 issue 關掉，等遇到新問題再開新的吧。

**Comment by fei0316** [comment]
我平常沒太多轉換的需要，而且又開學了，沒太多測試的機會。要是你用了一段時間沒問題的話告訴我一下，我到時候再試試就更新Google play。

**Comment by fei0316** [comment]
剛剛把一些小問題修復後發佈Google play了，不知可否更改一下評價？ :)

**Comment by AkazaRenn** [comment]
@fei0316 沒問題！剛剛去修改掉了
